# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale                   : "en-US"
title                    : "Eli Ben-Michael"
title_separator          : "-"
name: "Eli Ben-Michael"
description: "Academic and personal site for Eli Ben-Michael"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ebenmichael.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


# Site Author
author:
  name             : "Eli Ben-Michael"
  avatar           : "/assets/images/me.jpg"
  bio              : "Second year statistics PhD student at Berkeley."
  location         : "Berkeley, CA"
  email            : 
  uri              :
  github           : "ebenmichael"
  linkedin         : "eli-ben-michael-7b139498"
  twitter          : "EliBenMichael"

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Social Sharing
twitter:
  username : "EliBenMichael"

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/


theme: minimal-mistakes-jekyll
gems:
  - jekyll-feed
include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock

paginate: 5

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


defaults:
  #_posts
  - scope:
      path: ""
      type: posts
    values:
      layot: single
      comments: false
      author_profile: true
      sidebar: true